// mvp-angular/src/app/pages/admin.component.ts
import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ActivityService, VendorEngagement } from "../core/activity.service";
import { VendorAdminService } from "../core/vendor-admin.service";
import { ActivityEvent } from "../core/models";
import { fmtDateTime, fmtNumber, relativeTime } from "../core/format";
import { HBarsComponent, TrendChartComponent } from "../components/charts.component";
import { RouterLink } from "@angular/router";

interface UserRow { name: string; email: string; logins: number; views: number; minutes: number; reportsPulled: number; csvExports: number; lastActive: number; }

@Component({
  selector: "app-admin",
  standalone: true,
  imports: [CommonModule, RouterLink, TrendChartComponent, HBarsComponent],
  template: `
    <div class="page-head">
      <h1>Admin — Vendor Engagement</h1>
      <p>How brands and manufacturers use Market Insights and Premium Placement. First-party activity tracking (modeled on Periscope Usage Data).</p>
    </div>

    <div class="tgl" style="margin-bottom:16px">
      <button [class.on]="prod === 'mi'" (click)="prod = 'mi'">Market Insights</button>
      <button [class.on]="prod === 'pp'" (click)="prod = 'pp'">Premium Placement</button>
    </div>

    <div *ngIf="prod === 'mi'">
    <div class="grid c4" style="margin-bottom:16px">
      <div class="pcard kpi"><div class="label">Total logins</div><div class="value">{{ n(summary.totalLogins) }}</div><div class="delta flat">last 30 days</div></div>
      <div class="pcard kpi"><div class="label">Active brands</div><div class="value">{{ n(summary.activeVendors) }}</div><div class="delta flat">signed in ≥ 1 time</div></div>
      <div class="pcard kpi"><div class="label">Reports pulled</div><div class="value">{{ n(summary.reportsPulled) }}</div><div class="delta flat">on-demand + scheduled</div></div>
      <div class="pcard kpi"><div class="label">CSV extracts</div><div class="value">{{ n(summary.csvExports) }}</div><div class="delta flat">data downloads</div></div>
    </div>

    <div class="grid c2">
      <div class="pcard span2">
        <div class="hd" style="display:flex;justify-content:space-between;align-items:flex-start">
          <div><div class="t">Daily logins</div><div class="s">Logins per day · {{ rangeLabel }}</div></div>
          <div style="display:flex;gap:6px;align-items:center;flex-wrap:wrap">
            <div class="tgl">
              <button *ngFor="let r of ranges" [class.on]="rangeKey === r.k" (click)="setRange(r.k)">{{ r.l }}</button>
            </div>
            <input *ngIf="rangeKey === 'custom'" class="minput" type="date" [value]="cStart" (change)="onCustom($event, 's')" />
            <input *ngIf="rangeKey === 'custom'" class="minput" type="date" [value]="cEnd" (change)="onCustom($event, 'e')" />
          </div>
        </div>
        <div class="bd"><app-trend [points]="loginPoints" [gridlines]="true"></app-trend></div>
      </div>

      <div class="pcard"><div class="hd"><div class="t">Most-viewed dashboards</div><div class="s">By number of views</div></div>
        <div class="bd"><app-hbars [rows]="topDashRows" [money]="false"></app-hbars></div>
      </div>

      <div class="pcard"><div class="hd"><div class="t">Recent activity</div><div class="s">Live event feed</div></div>
        <div class="bd">
          <div *ngFor="let e of recent" style="display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:13px;padding:4px 0">
            <span style="display:flex;gap:8px;align-items:center;min-width:0">
              <span class="tag" [ngClass]="e.type">{{ label(e.type) }}</span>
              <b>{{ e.vendorName }}</b>
              <span class="muted" *ngIf="e.target" style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">· {{ e.target }}</span>
            </span>
            <span class="muted" [title]="dt(e.ts)" style="flex-shrink:0">{{ rel(e.ts) }}</span>
          </div>
        </div>
      </div>

      <div class="pcard span2"><div class="hd"><div class="t">Brand engagement</div><div class="s">Click a brand to expand its users</div></div>
        <div class="bd">
          <table class="ptbl">
            <thead><tr><th>Brand</th><th class="num">Logins</th><th class="num">Views</th><th class="num">Minutes</th><th class="num">Reports</th><th class="num">CSVs</th><th class="num">Last active</th></tr></thead>
            <tbody>
              <ng-container *ngFor="let v of engagement">
                <tr (click)="toggle(v.vendorId)" style="cursor:pointer">
                  <td style="font-weight:600"><span style="color:var(--text-muted);font-size:11px;margin-right:4px">{{ expanded === v.vendorId ? "▾" : "▸" }}</span>{{ v.vendorName }}</td>
                  <td class="num">{{ n(v.logins) }}</td>
                  <td class="num">{{ n(v.views) }}</td>
                  <td class="num">{{ n(v.minutes) }}</td>
                  <td class="num">{{ n(v.reportsPulled) }}</td>
                  <td class="num">{{ n(v.csvExports) }}</td>
                  <td class="num muted">{{ v.lastActive ? rel(v.lastActive) : "—" }}</td>
                </tr>
                <tr *ngIf="expanded === v.vendorId">
                  <td colspan="7" style="background:var(--surface-2);padding:0">
                    <table class="ptbl" style="margin:0">
                      <thead><tr><th style="padding-left:30px">User</th><th class="num">Logins</th><th class="num">Views</th><th class="num">Minutes</th><th class="num">Reports</th><th class="num">CSVs</th><th class="num">Last active</th></tr></thead>
                      <tbody>
                        <tr *ngFor="let u of usersFor(v.vendorName)" [routerLink]="['/admin/vendors/user', u.email]" style="cursor:pointer">
                          <td style="padding-left:30px">{{ u.name }}</td>
                          <td class="num">{{ n(u.logins) }}</td>
                          <td class="num">{{ n(u.views) }}</td>
                          <td class="num">{{ n(u.minutes) }}</td>
                          <td class="num">{{ n(u.reportsPulled) }}</td>
                          <td class="num">{{ n(u.csvExports) }}</td>
                          <td class="num muted">{{ u.lastActive ? rel(u.lastActive) : "—" }}</td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </ng-container>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    </div>

    <div *ngIf="prod === 'pp'">
      <div class="grid c4" style="margin-bottom:16px">
        <div class="pcard kpi"><div class="label">Ad impressions</div><div class="value">—</div><div class="delta flat">Spotlight + Featured</div></div>
        <div class="pcard kpi"><div class="label">Clicks</div><div class="value">—</div><div class="delta flat">all placements</div></div>
        <div class="pcard kpi"><div class="label">Click-through rate</div><div class="value">—</div><div class="delta flat">clicks ÷ impressions</div></div>
        <div class="pcard kpi"><div class="label">Active advertisers</div><div class="value">—</div><div class="delta flat">running placements</div></div>
      </div>
      <!-- TODO(premium-placement): wire real PP activity here once the advertiser (user) view is scoped —
           Spotlight live from AdButler, Featured Products from its source. NO synthetic data until then. -->
      <div class="pcard">
        <div class="hd"><div class="t">Premium Placement activity</div><div class="s">Impressions, clicks &amp; advertiser engagement across Spotlight &amp; Featured Products</div></div>
        <div class="bd" style="padding:30px;text-align:center;color:var(--text-muted)">
          <div style="font-size:14px;font-weight:600;margin-bottom:6px">No activity to show yet</div>
          <div style="font-size:13px;max-width:560px;margin:0 auto">Premium Placement activity will populate here once the advertiser (user) view is built. Spotlight metrics will come live from AdButler; Featured Products impressions/clicks are pending their data source. No sample data is shown.</div>
        </div>
      </div>
    </div>
  `,
})
export class AdminComponent {
  private activity = inject(ActivityService);
  private va = inject(VendorAdminService);

  summary = this.activity.getSummary(30);
  topDashRows = this.activity.getTopDashboards(30).map((d) => ({ label: d.name, value: d.views }));
  engagement: VendorEngagement[] = this.activity.getVendorEngagement(30);
  recent: ActivityEvent[] = this.activity.getRecentEvents(14);
  loginPoints: { label: string; value: number }[] = [];

  ranges = [{ k: "all", l: "All time" }, { k: "ytd", l: "YTD" }, { k: "mtd", l: "MTD" }, { k: "wtd", l: "WTD" }, { k: "custom", l: "Custom" }];
  rangeKey = "all";
  prod: "mi" | "pp" = "mi";  // which product line's activity is shown
  cStart = new Date(Date.now() - 14 * 86400000).toISOString().slice(0, 10);
  cEnd = new Date().toISOString().slice(0, 10);
  expanded: string | null = null;

  n = fmtNumber;
  rel = relativeTime;
  dt = fmtDateTime;

  constructor() { this.recompute(); }

  get rangeLabel(): string {
    return (this.ranges.find((r) => r.k === this.rangeKey) || this.ranges[0]).l;
  }
  get rangeDays(): number {
    const now = new Date();
    const DAY = 86400000;
    if (this.rangeKey === "ytd") return Math.ceil((now.getTime() - new Date(now.getFullYear(), 0, 1).getTime()) / DAY) + 1;
    if (this.rangeKey === "mtd") return now.getDate();
    if (this.rangeKey === "wtd") return now.getDay() + 1;
    if (this.rangeKey === "custom") return Math.max(1, Math.ceil((now.getTime() - new Date(this.cStart).getTime()) / DAY));
    return 60;
  }
  setRange(k: string): void { this.rangeKey = k; this.recompute(); }
  onCustom(ev: Event, which: "s" | "e"): void {
    const v = (ev.target as HTMLInputElement).value;
    if (which === "s") this.cStart = v; else this.cEnd = v;
    this.recompute();
  }
  private recompute(): void {
    this.loginPoints = this.activity.getActivityByDay(this.rangeDays).map((d) => ({ label: d.date.slice(5), value: d.logins }));
  }

  toggle(vendorId: string): void { this.expanded = this.expanded === vendorId ? null : vendorId; }
  usersFor(name: string): UserRow[] {
    const us = this.va.usersForBrandName(name);
    const bd = this.activity.userBreakdown(us.map((u) => u.email), this.rangeDays);
    return us.map((u, i) => ({ name: u.name, ...bd[i] }));
  }
  label(t: string): string {
    return { login: "Login", dashboard_view: "Viewed", report_pull: "Report", csv_export: "CSV" }[t] || t;
  }
}

// mvp-app/app/(app)/admin/page.tsx
import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import {
  getActivityByDay,
  getRecentEvents,
  getSummary,
  getTopDashboards,
  getVendorEngagement,
} from "@/lib/analytics/events";
import { AdminActivityChart, TopDashboardsBar } from "@/components/charts";
import { Card, KpiCard } from "@/components/ui";
import { fmtDate, fmtNumber, relativeTime } from "@/lib/format";

const TYPE_LABEL: Record<string, string> = {
  login: "Login",
  dashboard_view: "Viewed",
  report_pull: "Report",
  csv_export: "CSV",
};

export default function AdminPage() {
  const session = getSession()!;
  if (session.role !== "admin") redirect("/");

  const days = 30;
  const summary = getSummary(days);
  const byDay = getActivityByDay(days);
  const topDash = getTopDashboards(days);
  const engagement = getVendorEngagement(days);
  const recent = getRecentEvents(14);

  return (
    <>
      <div className="page-head">
        <h1>Portal View — Vendor Engagement</h1>
        <p>
          How brands and manufacturers are using Vendor Insights. Last {days} days · first-party activity tracking
          (modeled on Periscope Usage Data).
        </p>
      </div>

      <div className="grid cols-4" style={{ marginBottom: 16 }}>
        <KpiCard label="Total logins" value={fmtNumber(summary.totalLogins)} hint={`last ${days} days`} />
        <KpiCard label="Active brands" value={fmtNumber(summary.activeVendors)} hint="signed in ≥ 1 time" />
        <KpiCard label="Reports pulled" value={fmtNumber(summary.reportsPulled)} hint="on-demand + scheduled" />
        <KpiCard label="CSV extracts" value={fmtNumber(summary.csvExports)} hint="data downloads" />
      </div>
      <div className="grid cols-2" style={{ marginBottom: 16 }}>
        <KpiCard label="Time on site" value={`${summary.timeOnSiteHours.toFixed(1)} h`} hint="total across all brands" />
        <KpiCard label="Avg session" value={`${summary.avgSessionMin.toFixed(1)} min`} hint="per dashboard view" />
      </div>

      <div className="grid cols-2">
        <Card className="span-2" title="Daily activity" sub="Logins (bars) and minutes on site (line)">
          <AdminActivityChart data={byDay} />
        </Card>

        <Card title="Most-viewed dashboards" sub="By number of views">
          <TopDashboardsBar data={topDash} />
        </Card>

        <Card title="Recent activity" sub="Live event feed">
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {recent.map((e) => (
              <div key={e.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, fontSize: 13 }}>
                <div style={{ display: "flex", gap: 8, alignItems: "center", minWidth: 0 }}>
                  <span className={`tag-type t-${e.type}`}>{TYPE_LABEL[e.type]}</span>
                  <span style={{ fontWeight: 600 }}>{e.vendorName}</span>
                  {e.target && <span className="muted" style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>· {e.target}</span>}
                </div>
                <span className="muted" title={fmtDate(e.ts)} style={{ flexShrink: 0 }}>
                  {relativeTime(e.ts)}
                </span>
              </div>
            ))}
          </div>
        </Card>

        <Card className="span-2" title="Brand engagement" sub="Per-brand usage over the period">
          <table className="tbl">
            <thead>
              <tr>
                <th>Brand</th>
                <th className="num">Logins</th>
                <th className="num">Dashboard views</th>
                <th className="num">Minutes on site</th>
                <th className="num">Reports</th>
                <th className="num">CSV extracts</th>
                <th className="num">Last active</th>
              </tr>
            </thead>
            <tbody>
              {engagement.map((v) => (
                <tr key={v.vendorId}>
                  <td style={{ fontWeight: 600 }}>{v.vendorName}</td>
                  <td className="num">{fmtNumber(v.logins)}</td>
                  <td className="num">{fmtNumber(v.views)}</td>
                  <td className="num">{fmtNumber(v.minutes)}</td>
                  <td className="num">{fmtNumber(v.reportsPulled)}</td>
                  <td className="num">{fmtNumber(v.csvExports)}</td>
                  <td className="num muted">{v.lastActive ? relativeTime(v.lastActive) : "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>
      </div>
    </>
  );
}
